# Generated by Django 4.0.2 on 2023-07-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_gamescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='resume_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
