# Generated by Django 4.0.2 on 2023-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_user_college_name_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume_link',
            field=models.CharField(max_length=256),
        ),
    ]
