# Generated by Django 4.0.2 on 2023-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_drives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_name',
        ),
        migrations.AddField(
            model_name='user',
            name='College_Name',
            field=models.CharField(choices=[('MTIEAT', 'Mother Theresa Institure'), ('F', 'Female')], default='x', max_length=10),
        ),
    ]
