# Generated by Django 4.0.2 on 2023-07-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_remove_user_college_name_user_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='College_Name',
            new_name='college_name',
        ),
    ]
