# Generated by Django 4.0.2 on 2023-07-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_rename_college_name_user_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_name',
            field=models.CharField(choices=[('MTIEAT', 'Mother Theresa Institure')], default='x', max_length=10),
        ),
    ]
