# Generated by Django 4.0.2 on 2023-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_user_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_name',
            field=models.CharField(choices=[('Select', 'Select'), ('MTIEAT', 'Mother Theresa Institure')], default='x', max_length=10),
        ),
    ]
