# Generated by Django 4.0.2 on 2023-07-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_user_college_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=32)),
                ('drive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.drives')),
                ('enrolled_students', models.ManyToManyField(to='product.User')),
            ],
        ),
    ]
