# Generated by Django 4.0.2 on 2023-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, null=True, to='product.User'),
        ),
    ]
