# Generated by Django 4.0.2 on 2023-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_drives_enrolled_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='enrolled_students',
            new_name='selected_students',
        ),
        migrations.RemoveField(
            model_name='round',
            name='name',
        ),
        migrations.AddField(
            model_name='round',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
