# Generated by Django 4.0.2 on 2023-07-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_rename_enrolled_students_round_selected_students_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('drive_id', 'number')},
        ),
    ]
