# Generated by Django 4.0.2 on 2023-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_alter_round_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
