# Generated by Django 4.0.2 on 2023-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_drives_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='selected_students',
            field=models.ManyToManyField(blank=True, null=True, to='product.User'),
        ),
    ]
