# Generated by Django 4.0.2 on 2023-07-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_alter_round_selected_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='description',
        ),
    ]
