# Generated by Django 4.0.2 on 2023-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_user_aadhar_number_user_dept_user_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_name',
            field=models.CharField(choices=[('Select', 'Select'), ('MTIEAT', 'Mother Theresa Institure')], default='MTIEAT', max_length=10),
        ),
    ]
