# Generated by Django 4.0.2 on 2023-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_alter_user_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ST', 'Student'), ('TPO', 'Tpo')], default='ST', max_length=3),
        ),
    ]
