# Generated by Django 4.0.2 on 2023-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(blank=True, choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CO', 'Completed'), ('CA', 'Cancelled')], max_length=2, null=True),
        ),
    ]
