# Generated by Django 4.0.2 on 2023-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ST', 'Student'), ('TPO', 'Tpo'), ('HOD', 'HOD')], default='ST', max_length=3),
        ),
    ]
