# Generated by Django 4.0.2 on 2023-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
