# Generated by Django 5.0.1 on 2024-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_alter_user_resume_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('NAC', 'Not Accepted')], default='NAC', max_length=3),
        ),
    ]
