# Generated by Django 5.0.1 on 2024-08-13 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('hod_id', models.ForeignKey(limit_choices_to={'type': 'HOD'}, on_delete=django.db.models.deletion.CASCADE, related_name='hod_approvals', to='product.user')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='product.user')),
            ],
        ),
    ]
