# Generated by Django 5.0.1 on 2024-08-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=10),
        ),
    ]
