# Generated by Django 5.0.1 on 2024-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_drives_role_drives_year_user_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(default='21hr1a05a4', max_length=10),
        ),
    ]
