# Generated by Django 5.0.1 on 2024-08-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_alter_user_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='drives',
            name='year',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
