# Generated by Django 5.0.1 on 2024-08-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_user_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('dept', 'Department'), ('clg_name', 'College Name')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='approval',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
