# Generated by Django 5.0.1 on 2024-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_approval_approval_type_approval_new_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
