# Generated by Django 5.0.1 on 2024-08-15 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='stu_id',
        ),
        migrations.AddField(
            model_name='approval',
            name='roll_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='stu_email',
            field=models.EmailField(default='acb@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='stu_name',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
    ]
