# Generated by Django 5.0.1 on 2024-08-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_remove_approval_stu_id_approval_roll_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
    ]
