# Generated by Django 5.0.1 on 2024-08-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_rename_type_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('new_stu_account', 'stu_account'), ('percentage', 'Percentage'), ('dept', 'Department'), ('clg_name', 'College Name')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='hod_id',
            field=models.ForeignKey(limit_choices_to={'user_type': 'HOD'}, on_delete=django.db.models.deletion.CASCADE, related_name='hod_approvals', to='product.user'),
        ),
    ]
