# Generated by Django 5.0.1 on 2024-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_alter_approval_approval_type_alter_approval_hod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='id',
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
