# Generated by Django 5.0.1 on 2024-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_user_reset_password_alter_drives_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, default=2024, null=True),
        ),
    ]
