# Generated by Django 5.0.1 on 2024-08-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_user_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='drives',
            name='selected_students',
            field=models.ManyToManyField(blank=True, related_name='selected_drives', to='product.user'),
        ),
        migrations.AlterField(
            model_name='drives',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_drives', to='product.user'),
        ),
    ]
