# Generated by Django 5.0.1 on 2024-08-18 14:09

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_alter_user_resume_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=product.models.upload_profile),
        ),
    ]
