# Generated by Django 5.0.1 on 2024-08-19 01:51

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='jd_link',
            field=models.FileField(blank=True, null=True, upload_to=product.models.upload_jd),
        ),
    ]
